version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:5000/backend"
      REACT_APP_BACKEND_ALL_TICKETS_URL: "http://localhost:4000/alltickets"
    depends_on:
      - backend1
      - backend-getalltickets
    networks:
      - app-network

  backend1:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  backend-getalltickets:
    build: ./backend-getalltickets
    ports:
      - "4000:4000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
